apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bigquery-controller
  labels:
    name: bigquery-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: bigquery-controller
    spec:
      containers:
      - name: bigquery
        image: gcr.io/google-samples/pubsub-bq-pipe:v5
        env:
        - name: PROCESSINGSCRIPT
          value: pubsub-to-bigquery
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: projects/vivid-fragment-222314/topics/mypubsub
        # Change this to your project ID.
        - name: PROJECT_ID
          value: vivid-fragment-222314
        # Change the following two settings to your dataset and table.
        - name: BQ_DATASET
          value: mydataset
        - name: BQ_TABLE
          value: twitter
