# YAML file
# twitter-secret-env.yaml
apiVersion: v1
kind: Secret
metadata:
  name: twitter-secret-env
type: Opaque
data:
  consumerkey: bDgwS0J5SEUxaUpXaVpJVnpPbVdhUlJMRg==
  consumersecret: VVk4c0xXak9WZFB6TElHZnVOd2VDeHRzQTYzWmNXaGJVMXI4dmJrVmF4ZnpmRnU4dEU=
  accesstoken: MTAzMjcxNzYwODA2NjQ2OTg4OC1EY1dsaWdDV2Y3YzVtM3g4TXNqQmF6cnNsRWtGMHE=
  accesstokensec: emlJN1ZVTlRHR21yYmNmUnFreDdURE50RHE4WjRlZnZrSFpUM2Q0c1VBM2k4
