apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub-secrets
#        image: gcr.io/google-samples/pubsub-bq-pipe:v5
        image: gcr.io/vivid-fragment-222314/poc_092019
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub_secrets
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: projects/vivid-fragment-222314/topics/mypubsub
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          valueFrom:
            secretKeyRef:
              name: twitter-secret-env
              key: consumerkey
        - name: CONSUMERSECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret-env
              key: consumersecret
        - name: ACCESSTOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-secret-env
              key: accesstoken
        - name: ACCESSTOKENSEC
          valueFrom:
            secretKeyRef:
              name: twitter-secret-env
              key: accesstokensec
        - name: TWSTREAMMODE
          value: sample
